---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
spec: 
  replicas: 2
  selector:
    matchLabels:
      name: elastic
  template:
    metadata:
      labels:
        name: elastic
    spec: 
      terminationGracePeriodSeconds: 30
      containers:
      - name: elastic
        image: docker.io/elasticsearch:7.3.0
        ports:
        - containerPort: 9200